export type {
  InvestigationBuildOptions,
  InvestigationPayload,
} from './mega/contracts';
export {
  MASTER_INVESTIGATION_ORCHESTRATOR_V5,
  SHARED_ABSENCE_SEMANTICS_BLOCK,
  SHARED_ANTI_R_INFLATION_RULES_BLOCK,
  SHARED_BUSINESS_TRANSLATION_ENGINE_BLOCK,
  SHARED_COST_OF_DELAY_ENGINE_BLOCK,
  SHARED_CROSS_PROMPT_ARBITRATION_BLOCK,
  SHARED_DISCREPANCY_HUNTER_BLOCK,
  SHARED_ENTITY_RESOLUTION_BLOCK,
  SHARED_EVIDENCE_HIERARCHY_BLOCK,
  SHARED_EXECUTIVE_PRESSURE_ENGINE_BLOCK,
  SHARED_FINAL_RECONCILIATION_BLOCK,
  SHARED_FOUNDATION_BLOCK_V5,
  SHARED_INCUMBENT_WEAKNESS_ENGINE_BLOCK,
  SHARED_PARSER_GUARD_BLOCK,
  SHARED_RECENCY_POLICY_BLOCK,
} from './mega/foundation';
export {
  PROMPT_MAPEAMENTO_DECISORES_GOD_MODE,
  PROMPT_ORCAMENTO_JANELA_GOD_MODE,
  PROMPT_RADAR_EXPANSAO_GOD_MODE,
  PROMPT_RAIO_X_OPERACIONAL_ATAQUE,
  PROMPT_RH_SINDICATOS_GOD_MODE,
  PROMPT_RISCOS_COMPLIANCE_GOD_MODE,
  PROMPT_TECH_STACK_GOD_MODE_ATAQUE,
} from './mega/specialist-prompts';
export {
  ALL_SPECIALIST_PROMPTS,
  INVESTIGATION_MODE_BLOCKS,
  PROMPT_VERSION,
  SELLER_BRIEF_MODULE_OUTPUT_CONTRACT,
  SHARED_FOUNDATION_BLOCK,
  buildInvestigationHiddenPrompt,
  buildLegacyCompatibleHiddenPrompt,
} from './mega/builders';
export { default } from './mega/builders';
