-- Teste PostgreSQL versionado para retenção e índices de scout_diagnostics.
-- Executar somente em banco descartável com o nome exato abaixo:
--   psql -v ON_ERROR_STOP=1 -d novoapp_scout_diagnostics_test \
--     -f scripts/test_scout_diagnostics_retention.sql

BEGIN;

DO $$
BEGIN
  IF current_database() <> 'novoapp_scout_diagnostics_test' THEN
    RAISE EXCEPTION 'FALHA: execute somente no banco descartável novoapp_scout_diagnostics_test';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN BYPASSRLS;
  ELSE
    ALTER ROLE service_role WITH BYPASSRLS;
  END IF;
END $$;

DROP TABLE IF EXISTS public.scout_diagnostics_maintenance CASCADE;
DROP TABLE IF EXISTS public.scout_diagnostics CASCADE;

CREATE TABLE public.scout_diagnostics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  run_id text NOT NULL,
  session_id text,
  severity text NOT NULL DEFAULT 'info'
);

CREATE INDEX idx_scout_diagnostics_created_at ON public.scout_diagnostics (created_at);
CREATE INDEX idx_scout_diagnostics_run_id ON public.scout_diagnostics (run_id);
CREATE INDEX idx_scout_diagnostics_session_id ON public.scout_diagnostics (session_id);
CREATE INDEX idx_scout_diagnostics_severity ON public.scout_diagnostics (severity);
CREATE INDEX idx_sd_created_at ON public.scout_diagnostics (created_at);
CREATE INDEX idx_sd_run_id ON public.scout_diagnostics (run_id);
CREATE INDEX idx_sd_session_id ON public.scout_diagnostics (session_id);
CREATE INDEX idx_sd_severity ON public.scout_diagnostics (severity);

\i supabase/migrations/20260730090000_scout_diagnostics_opportunistic_retention.sql

UPDATE pg_index
SET indisvalid = false,
    indisready = false,
    indislive = false
WHERE indexrelid = 'public.idx_scout_diagnostics_created_at'::regclass;

\i supabase/migrations/20260730090100_remove_duplicate_scout_diagnostics_indexes.sql

DO $$
BEGIN
  IF to_regclass('public.idx_sd_created_at') IS NULL THEN
    RAISE EXCEPTION 'FALHA: keeper inválido ou não pronto removeu índice válido';
  END IF;
END $$;

UPDATE pg_index
SET indisvalid = true,
    indisready = true,
    indislive = true
WHERE indexrelid = 'public.idx_scout_diagnostics_created_at'::regclass;

\i supabase/migrations/20260730090100_remove_duplicate_scout_diagnostics_indexes.sql

DO $$
DECLARE
  duplicate_count integer;
  canonical_count integer;
BEGIN
  IF has_function_privilege('anon', 'public.cleanup_scout_diagnostics_opportunistic(integer,integer)', 'EXECUTE') THEN
    RAISE EXCEPTION 'FALHA: anon possui EXECUTE na função de retenção';
  END IF;
  IF has_function_privilege('authenticated', 'public.cleanup_scout_diagnostics_opportunistic(integer,integer)', 'EXECUTE') THEN
    RAISE EXCEPTION 'FALHA: authenticated possui EXECUTE na função de retenção';
  END IF;
  IF NOT has_function_privilege('service_role', 'public.cleanup_scout_diagnostics_opportunistic(integer,integer)', 'EXECUTE') THEN
    RAISE EXCEPTION 'FALHA: service_role não possui EXECUTE na função de retenção';
  END IF;

  IF has_table_privilege('anon', 'public.scout_diagnostics_maintenance',
      'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER') THEN
    RAISE EXCEPTION 'FALHA: anon possui acesso à tabela de manutenção';
  END IF;
  IF has_table_privilege('authenticated', 'public.scout_diagnostics_maintenance',
      'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER') THEN
    RAISE EXCEPTION 'FALHA: authenticated possui acesso à tabela de manutenção';
  END IF;

  SELECT count(*) INTO duplicate_count
  FROM pg_indexes
  WHERE schemaname = 'public'
    AND tablename = 'scout_diagnostics'
    AND indexname LIKE 'idx_sd_%';
  IF duplicate_count <> 0 THEN
    RAISE EXCEPTION 'FALHA: % índices idx_sd_* permaneceram', duplicate_count;
  END IF;

  SELECT count(*) INTO canonical_count
  FROM pg_indexes
  WHERE schemaname = 'public'
    AND tablename = 'scout_diagnostics'
    AND indexname IN (
      'idx_scout_diagnostics_created_at',
      'idx_scout_diagnostics_run_id',
      'idx_scout_diagnostics_session_id',
      'idx_scout_diagnostics_severity'
    );
  IF canonical_count <> 4 THEN
    RAISE EXCEPTION 'FALHA: esperados 4 índices canônicos, encontrados %', canonical_count;
  END IF;
END $$;

INSERT INTO public.scout_diagnostics (created_at, run_id, session_id, severity)
SELECT now() - interval '15 days', 'old-' || value, 'session-old', 'info'
FROM generate_series(1, 10001) AS value;

INSERT INTO public.scout_diagnostics (created_at, run_id, session_id, severity)
VALUES (now() - interval '13 days', 'recent', 'session-recent', 'info');

DO $$
DECLARE
  deleted_first integer;
  deleted_second integer;
  old_remaining integer;
  recent_remaining integer;
BEGIN
  SET LOCAL ROLE service_role;
  SELECT public.cleanup_scout_diagnostics_opportunistic(14, 500) INTO deleted_first;
  SELECT public.cleanup_scout_diagnostics_opportunistic(14, 500) INTO deleted_second;
  RESET ROLE;

  IF deleted_first <= 0 OR deleted_first > 10000 OR deleted_first % 500 <> 0 THEN
    RAISE EXCEPTION 'FALHA: primeira execução deveria excluir múltiplo de 500 entre 1 e 10000, excluiu %', deleted_first;
  END IF;
  IF deleted_second <> 0 THEN
    RAISE EXCEPTION 'FALHA: segunda execução no mesmo dia deveria retornar 0, retornou %', deleted_second;
  END IF;

  SELECT count(*) INTO old_remaining
  FROM public.scout_diagnostics
  WHERE created_at < now() - interval '14 days';
  IF old_remaining <> 10001 - deleted_first THEN
    RAISE EXCEPTION 'FALHA: antigas restantes deveriam ser %, restaram %', 10001 - deleted_first, old_remaining;
  END IF;

  SELECT count(*) INTO recent_remaining
  FROM public.scout_diagnostics
  WHERE run_id = 'recent';
  IF recent_remaining <> 1 THEN
    RAISE EXCEPTION 'FALHA: linha recente não foi preservada';
  END IF;
END $$;

DO $$
BEGIN
  BEGIN
    PERFORM public.cleanup_scout_diagnostics_opportunistic(14, 0);
    RAISE EXCEPTION 'FALHA: batch_size inválido deveria falhar';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLERRM <> 'invalid retention parameters' THEN
        RAISE;
      END IF;
  END;
END $$;

ROLLBACK;

\echo 'PASS: scout_diagnostics retention runtime assertions'
