-- History marker.
-- Esta versão já está representada pelo baseline
-- 20260501000000_production_schema_baseline.sql.
-- Mantida para compatibilidade com o migration history de Produção.
-- Não adicionar DDL ou DML neste arquivo.
